/**
 * All Dutch municipalities (gemeenten) — auto-generated from Gemeenten.csv
 * Total: 342 gemeenten
 */

export interface GemeenteEntry {
  id: string;
  name: string;
  officialName: string;
  websiteUrl: string;
}

export const alleGemeenten: GemeenteEntry[] = [
  {
    id: 'aa-en-hunze',
    name: 'Aa en Hunze',
    officialName: 'Gemeente Aa en Hunze',
    websiteUrl: 'https://www.aaenhunze.nl',
  },
  {
    id: 'aalsmeer',
    name: 'Aalsmeer',
    officialName: 'Gemeente Aalsmeer',
    websiteUrl: 'https://www.aalsmeer.nl',
  },
  {
    id: 'aalten',
    name: 'Aalten',
    officialName: 'Gemeente Aalten',
    websiteUrl: 'https://www.aalten.nl',
  },
  {
    id: 'achtkarspelen',
    name: 'Achtkarspelen',
    officialName: 'Gemeente Achtkarspelen',
    websiteUrl: 'https://www.achtkarspelen.nl',
  },
  {
    id: 'alblasserdam',
    name: 'Alblasserdam',
    officialName: 'Gemeente Alblasserdam',
    websiteUrl: 'https://www.alblasserdam.nl',
  },
  {
    id: 'albrandswaard',
    name: 'Albrandswaard',
    officialName: 'Gemeente Albrandswaard',
    websiteUrl: 'https://www.albrandswaard.nl',
  },
  {
    id: 'alkmaar',
    name: 'Alkmaar',
    officialName: 'Gemeente Alkmaar',
    websiteUrl: 'https://www.alkmaar.nl',
  },
  {
    id: 'almelo',
    name: 'Almelo',
    officialName: 'Gemeente Almelo',
    websiteUrl: 'https://www.almelo.nl',
  },
  {
    id: 'almere',
    name: 'Almere',
    officialName: 'Gemeente Almere',
    websiteUrl: 'https://www.almere.nl',
  },
  {
    id: 'alphen-aan-den-rijn',
    name: 'Alphen aan den Rijn',
    officialName: 'Gemeente Alphen aan den Rijn',
    websiteUrl: 'https://www.alphenaandenrijn.nl',
  },
  {
    id: 'alphen-chaam',
    name: 'Alphen-Chaam',
    officialName: 'Gemeente Alphen-Chaam',
    websiteUrl: 'https://www.alphen-chaam.nl',
  },
  {
    id: 'altena',
    name: 'Altena',
    officialName: 'Gemeente Altena',
    websiteUrl: 'https://www.gemeenteAltena.nl',
  },
  {
    id: 'ameland',
    name: 'Ameland',
    officialName: 'Gemeente Ameland',
    websiteUrl: 'https://www.ameland.nl',
  },
  {
    id: 'amersfoort',
    name: 'Amersfoort',
    officialName: 'Gemeente Amersfoort',
    websiteUrl: 'https://www.amersfoort.nl',
  },
  {
    id: 'amstelveen',
    name: 'Amstelveen',
    officialName: 'Gemeente Amstelveen',
    websiteUrl: 'https://www.amstelveen.nl',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    officialName: 'Gemeente Amsterdam',
    websiteUrl: 'https://www.amsterdam.nl',
  },
  {
    id: 'apeldoorn',
    name: 'Apeldoorn',
    officialName: 'Gemeente Apeldoorn',
    websiteUrl: 'https://www.apeldoorn.nl',
  },
  {
    id: 'arnhem',
    name: 'Arnhem',
    officialName: 'Gemeente Arnhem',
    websiteUrl: 'https://www.arnhem.nl',
  },
  {
    id: 'assen',
    name: 'Assen',
    officialName: 'Gemeente Assen',
    websiteUrl: 'https://www.assen.nl',
  },
  {
    id: 'asten',
    name: 'Asten',
    officialName: 'Gemeente Asten',
    websiteUrl: 'https://www.asten.nl',
  },
  {
    id: 'baarle-nassau',
    name: 'Baarle-Nassau',
    officialName: 'Gemeente Baarle-Nassau',
    websiteUrl: 'https://www.baarle-nassau.nl',
  },
  {
    id: 'baarn',
    name: 'Baarn',
    officialName: 'Gemeente Baarn',
    websiteUrl: 'https://www.baarn.nl',
  },
  {
    id: 'barendrecht',
    name: 'Barendrecht',
    officialName: 'Gemeente Barendrecht',
    websiteUrl: 'https://www.barendrecht.nl',
  },
  {
    id: 'barneveld',
    name: 'Barneveld',
    officialName: 'Gemeente Barneveld',
    websiteUrl: 'https://www.barneveld.nl',
  },
  {
    id: 'beek',
    name: 'Beek',
    officialName: 'Gemeente Beek',
    websiteUrl: 'https://www.gemeentebeek.nl',
  },
  {
    id: 'beekdaelen',
    name: 'Beekdaelen',
    officialName: 'Gemeente Beekdaelen',
    websiteUrl: 'https://www.beekdaelen.nl',
  },
  {
    id: 'beesel',
    name: 'Beesel',
    officialName: 'Gemeente Beesel',
    websiteUrl: 'https://www.beesel.nl',
  },
  {
    id: 'berg-en-dal',
    name: 'Berg en Dal',
    officialName: 'Gemeente Berg en Dal',
    websiteUrl: 'https://www.bergendal.nl',
  },
  {
    id: 'bergeijk',
    name: 'Bergeijk',
    officialName: 'Gemeente Bergeijk',
    websiteUrl: 'https://www.bergeijk.nl',
  },
  {
    id: 'bergen-l',
    name: 'Bergen (L)',
    officialName: 'Gemeente Bergen (L)',
    websiteUrl: 'https://www.bergen.nl',
  },
  {
    id: 'bergen-nh',
    name: 'Bergen NH',
    officialName: 'Gemeente Bergen (NH)',
    websiteUrl: 'https://www.bergen-nh.nl',
  },
  {
    id: 'bergen-op-zoom',
    name: 'Bergen op Zoom',
    officialName: 'Gemeente Bergen op Zoom',
    websiteUrl: 'https://www.bergenopzoom.nl',
  },
  {
    id: 'berkelland',
    name: 'Berkelland',
    officialName: 'Gemeente Berkelland',
    websiteUrl: 'https://www.gemeenteberkelland.nl',
  },
  {
    id: 'bernheze',
    name: 'Bernheze',
    officialName: 'Gemeente Bernheze',
    websiteUrl: 'https://www.bernheze.org',
  },
  {
    id: 'best',
    name: 'Best',
    officialName: 'Gemeente Best',
    websiteUrl: 'https://www.gemeentebest.nl',
  },
  {
    id: 'beuningen',
    name: 'Beuningen',
    officialName: 'Gemeente Beuningen',
    websiteUrl: 'https://www.beuningen.nl',
  },
  {
    id: 'beverwijk',
    name: 'Beverwijk',
    officialName: 'Gemeente Beverwijk',
    websiteUrl: 'https://www.beverwijk.nl',
  },
  {
    id: 'bladel',
    name: 'Bladel',
    officialName: 'Gemeente Bladel',
    websiteUrl: 'https://www.bladel.nl',
  },
  {
    id: 'blaricum',
    name: 'Blaricum',
    officialName: 'Gemeente Blaricum',
    websiteUrl: 'https://www.blaricum.nl',
  },
  {
    id: 'bloemendaal',
    name: 'Bloemendaal',
    officialName: 'Gemeente Bloemendaal',
    websiteUrl: 'https://www.bloemendaal.nl',
  },
  {
    id: 'bodegraven-reeuwijk',
    name: 'Bodegraven-Reeuwijk',
    officialName: 'Gemeente Bodegraven-Reeuwijk',
    websiteUrl: 'https://www.bodegraven-reeuwijk.nl',
  },
  {
    id: 'boekel',
    name: 'Boekel',
    officialName: 'Gemeente Boekel',
    websiteUrl: 'https://www.boekel.nl',
  },
  {
    id: 'borger-odoorn',
    name: 'Borger-Odoorn',
    officialName: 'Gemeente Borger-Odoorn',
    websiteUrl: 'https://www.borger-odoorn.nl',
  },
  {
    id: 'borne',
    name: 'Borne',
    officialName: 'Gemeente Borne',
    websiteUrl: 'https://www.borne.nl',
  },
  {
    id: 'borsele',
    name: 'Borsele',
    officialName: 'Gemeente Borsele',
    websiteUrl: 'https://www.borsele.nl',
  },
  {
    id: 'boxtel',
    name: 'Boxtel',
    officialName: 'Gemeente Boxtel',
    websiteUrl: 'https://www.boxtel.nl',
  },
  {
    id: 'breda',
    name: 'Breda',
    officialName: 'Gemeente Breda',
    websiteUrl: 'https://www.breda.nl',
  },
  {
    id: 'bronckhorst',
    name: 'Bronckhorst',
    officialName: 'Gemeente Bronckhorst',
    websiteUrl: 'https://www.bronckhorst.nl',
  },
  {
    id: 'brummen',
    name: 'Brummen',
    officialName: 'Gemeente Brummen',
    websiteUrl: 'https://www.brummen.nl',
  },
  {
    id: 'brunssum',
    name: 'Brunssum',
    officialName: 'Gemeente Brunssum',
    websiteUrl: 'https://www.brunssum.nl',
  },
  {
    id: 'bunnik',
    name: 'Bunnik',
    officialName: 'Gemeente Bunnik',
    websiteUrl: 'https://www.bunnik.nl',
  },
  {
    id: 'bunschoten',
    name: 'Bunschoten',
    officialName: 'Gemeente Bunschoten',
    websiteUrl: 'https://www.bunschoten.nl',
  },
  {
    id: 'buren',
    name: 'Buren',
    officialName: 'Gemeente Buren',
    websiteUrl: 'https://www.buren.nl',
  },
  {
    id: 'capelle-aan-den-ijssel',
    name: 'Capelle aan den IJssel',
    officialName: 'Gemeente Capelle aan den IJssel',
    websiteUrl: 'https://www.capelleaandenijssel.nl',
  },
  {
    id: 'castricum',
    name: 'Castricum',
    officialName: 'Gemeente Castricum',
    websiteUrl: 'https://www.castricum.nl',
  },
  {
    id: 'coevorden',
    name: 'Coevorden',
    officialName: 'Gemeente Coevorden',
    websiteUrl: 'https://www.coevorden.nl',
  },
  {
    id: 'cranendonck',
    name: 'Cranendonck',
    officialName: 'Gemeente Cranendonck',
    websiteUrl: 'https://www.cranendonck.nl',
  },
  {
    id: 'culemborg',
    name: 'Culemborg',
    officialName: 'Gemeente Culemborg',
    websiteUrl: 'https://www.culemborg.nl',
  },
  {
    id: 'dalfsen',
    name: 'Dalfsen',
    officialName: 'Gemeente Dalfsen',
    websiteUrl: 'https://www.dalfsen.nl',
  },
  {
    id: 'dantumadiel',
    name: 'Dantumadiel',
    officialName: 'Gemeente Dantumadiel',
    websiteUrl: 'https://www.dantumadiel.frl',
  },
  {
    id: 'de-bilt',
    name: 'De Bilt',
    officialName: 'Gemeente De Bilt',
    websiteUrl: 'https://www.debilt.nl',
  },
  {
    id: 'de-fryske-marren',
    name: 'De Fryske Marren',
    officialName: 'Gemeente De Fryske Marren',
    websiteUrl: 'https://www.defryskemarren.nl',
  },
  {
    id: 'de-ronde-venen',
    name: 'De Ronde Venen',
    officialName: 'Gemeente De Ronde Venen',
    websiteUrl: 'https://www.derondevenen.nl',
  },
  {
    id: 'de-wolden',
    name: 'De Wolden',
    officialName: 'Gemeente De Wolden',
    websiteUrl: 'https://dewolden.nl',
  },
  {
    id: 'delft',
    name: 'Delft',
    officialName: 'Gemeente Delft',
    websiteUrl: 'https://www.delft.nl',
  },
  {
    id: 'den-haag',
    name: 'Den Haag',
    officialName: 'Gemeente Den Haag',
    websiteUrl: 'https://www.denhaag.nl',
  },
  {
    id: 'den-helder',
    name: 'Den Helder',
    officialName: 'Gemeente Den Helder',
    websiteUrl: 'https://www.denhelder.nl',
  },
  {
    id: 'deurne',
    name: 'Deurne',
    officialName: 'Gemeente Deurne',
    websiteUrl: 'https://www.deurne.nl',
  },
  {
    id: 'deventer',
    name: 'Deventer',
    officialName: 'Gemeente Deventer',
    websiteUrl: 'https://www.deventer.nl',
  },
  {
    id: 'diemen',
    name: 'Diemen',
    officialName: 'Gemeente Diemen',
    websiteUrl: 'https://www.diemen.nl',
  },
  {
    id: 'dijk-en-waard',
    name: 'Dijk en Waard',
    officialName: 'Gemeente Dijk en Waard',
    websiteUrl: 'https://www.dijkenwaard.nl',
  },
  {
    id: 'dinkelland',
    name: 'Dinkelland',
    officialName: 'Gemeente Dinkelland',
    websiteUrl: 'https://www.dinkelland.nl',
  },
  {
    id: 'doesburg',
    name: 'Doesburg',
    officialName: 'Gemeente Doesburg',
    websiteUrl: 'https://www.doesburg.nl',
  },
  {
    id: 'doetinchem',
    name: 'Doetinchem',
    officialName: 'Gemeente Doetinchem',
    websiteUrl: 'https://www.doetinchem.nl',
  },
  {
    id: 'dongen',
    name: 'Dongen',
    officialName: 'Gemeente Dongen',
    websiteUrl: 'https://www.dongen.nl',
  },
  {
    id: 'dordrecht',
    name: 'Dordrecht',
    officialName: 'Gemeente Dordrecht',
    websiteUrl: 'https://www.dordrecht.nl',
  },
  {
    id: 'drechterland',
    name: 'Drechterland',
    officialName: 'Gemeente Drechterland',
    websiteUrl: 'https://www.drechterland.nl',
  },
  {
    id: 'drimmelen',
    name: 'Drimmelen',
    officialName: 'Gemeente Drimmelen',
    websiteUrl: 'https://www.drimmelen.nl',
  },
  {
    id: 'dronten',
    name: 'Dronten',
    officialName: 'Gemeente Dronten',
    websiteUrl: 'https://www.dronten.nl',
  },
  {
    id: 'druten',
    name: 'Druten',
    officialName: 'Gemeente Druten',
    websiteUrl: 'https://www.druten.nl',
  },
  {
    id: 'duiven',
    name: 'Duiven',
    officialName: 'Gemeente Duiven',
    websiteUrl: 'https://www.duiven.nl',
  },
  {
    id: 'echt-susteren',
    name: 'Echt-Susteren',
    officialName: 'Gemeente Echt-Susteren',
    websiteUrl: 'https://www.echt-susteren.nl',
  },
  {
    id: 'edam-volendam',
    name: 'Edam-Volendam',
    officialName: 'Gemeente Edam-Volendam',
    websiteUrl: 'https://www.edam-volendam.nl',
  },
  {
    id: 'ede',
    name: 'Ede',
    officialName: 'Gemeente Ede',
    websiteUrl: 'https://www.ede.nl',
  },
  {
    id: 'eemnes',
    name: 'Eemnes',
    officialName: 'Gemeente Eemnes',
    websiteUrl: 'https://www.eemnes.nl',
  },
  {
    id: 'eemsdelta',
    name: 'Eemsdelta',
    officialName: 'Gemeente Eemsdelta',
    websiteUrl: 'https://www.eemsdelta.nl',
  },
  {
    id: 'eersel',
    name: 'Eersel',
    officialName: 'Gemeente Eersel',
    websiteUrl: 'https://www.eersel.nl',
  },
  {
    id: 'eijsden-margraten',
    name: 'Eijsden-Margraten',
    officialName: 'Gemeente Eijsden-Margraten',
    websiteUrl: 'https://www.eijsden-margraten.nl',
  },
  {
    id: 'eindhoven',
    name: 'Eindhoven',
    officialName: 'Gemeente Eindhoven',
    websiteUrl: 'https://www.eindhoven.nl',
  },
  {
    id: 'elburg',
    name: 'Elburg',
    officialName: 'Gemeente Elburg',
    websiteUrl: 'https://www.elburg.nl',
  },
  {
    id: 'emmen',
    name: 'Emmen',
    officialName: 'Gemeente Emmen',
    websiteUrl: 'https://www.emmen.nl',
  },
  {
    id: 'enkhuizen',
    name: 'Enkhuizen',
    officialName: 'Gemeente Enkhuizen',
    websiteUrl: 'https://www.enkhuizen.nl',
  },
  {
    id: 'enschede',
    name: 'Enschede',
    officialName: 'Gemeente Enschede',
    websiteUrl: 'https://www.enschede.nl',
  },
  {
    id: 'epe',
    name: 'Epe',
    officialName: 'Gemeente Epe',
    websiteUrl: 'https://www.epe.nl',
  },
  {
    id: 'ermelo',
    name: 'Ermelo',
    officialName: 'Gemeente Ermelo',
    websiteUrl: 'https://www.ermelo.nl',
  },
  {
    id: 'etten-leur',
    name: 'Etten-Leur',
    officialName: 'Gemeente Etten-Leur',
    websiteUrl: 'https://www.etten-leur.nl',
  },
  {
    id: 'geertruidenberg',
    name: 'Geertruidenberg',
    officialName: 'Gemeente Geertruidenberg',
    websiteUrl: 'https://www.geertruidenberg.nl',
  },
  {
    id: 'geldrop-mierlo',
    name: 'Geldrop-Mierlo',
    officialName: 'Gemeente Geldrop-Mierlo',
    websiteUrl: 'https://www.geldrop-mierlo.nl',
  },
  {
    id: 'gemert-bakel',
    name: 'Gemert-Bakel',
    officialName: 'Gemeente Gemert-Bakel',
    websiteUrl: 'https://www.gemert-bakel.nl',
  },
  {
    id: 'gennep',
    name: 'Gennep',
    officialName: 'Gemeente Gennep',
    websiteUrl: 'https://www.gennep.nl',
  },
  {
    id: 'gilze-en-rijen',
    name: 'Gilze en Rijen',
    officialName: 'Gemeente Gilze en Rijen',
    websiteUrl: 'https://www.gilzerijen.nl',
  },
  {
    id: 'goeree-overflakkee',
    name: 'Goeree-Overflakkee',
    officialName: 'Gemeente Goeree-Overflakkee',
    websiteUrl: 'https://www.goeree-overflakkee.nl',
  },
  {
    id: 'goes',
    name: 'Goes',
    officialName: 'Gemeente Goes',
    websiteUrl: 'https://www.goes.nl',
  },
  {
    id: 'goirle',
    name: 'Goirle',
    officialName: 'Gemeente Goirle',
    websiteUrl: 'https://www.goirle.nl',
  },
  {
    id: 'gooise-meren',
    name: 'Gooise Meren',
    officialName: 'Gemeente Gooise Meren',
    websiteUrl: 'https://www.gooisemeren.nl',
  },
  {
    id: 'gorinchem',
    name: 'Gorinchem',
    officialName: 'Gemeente Gorinchem',
    websiteUrl: 'https://www.gorinchem.nl',
  },
  {
    id: 'gouda',
    name: 'Gouda',
    officialName: 'Gemeente Gouda',
    websiteUrl: 'https://www.gouda.nl',
  },
  {
    id: 'groningen',
    name: 'Groningen',
    officialName: 'Gemeente Groningen',
    websiteUrl: 'https://gemeente.groningen.nl',
  },
  {
    id: 'gulpen-wittem',
    name: 'Gulpen-Wittem',
    officialName: 'Gemeente Gulpen-Wittem',
    websiteUrl: 'https://www.gulpen-wittem.nl',
  },
  {
    id: 'haaksbergen',
    name: 'Haaksbergen',
    officialName: 'Gemeente Haaksbergen',
    websiteUrl: 'https://www.haaksbergen.nl',
  },
  {
    id: 'haarlem',
    name: 'Haarlem',
    officialName: 'Gemeente Haarlem',
    websiteUrl: 'https://www.haarlem.nl',
  },
  {
    id: 'haarlemmermeer',
    name: 'Haarlemmermeer',
    officialName: 'Gemeente Haarlemmermeer',
    websiteUrl: 'https://www.haarlemmermeer.nl',
  },
  {
    id: 'halderberge',
    name: 'Halderberge',
    officialName: 'Gemeente Halderberge',
    websiteUrl: 'https://www.halderberge.nl',
  },
  {
    id: 'hardenberg',
    name: 'Hardenberg',
    officialName: 'Gemeente Hardenberg',
    websiteUrl: 'https://www.hardenberg.nl',
  },
  {
    id: 'harderwijk',
    name: 'Harderwijk',
    officialName: 'Gemeente Harderwijk',
    websiteUrl: 'https://www.harderwijk.nl',
  },
  {
    id: 'hardinxveld-giessendam',
    name: 'Hardinxveld-Giessendam',
    officialName: 'Gemeente Hardinxveld-Giessendam',
    websiteUrl: 'https://www.hardinxveld-giessendam.nl',
  },
  {
    id: 'harlingen',
    name: 'Harlingen',
    officialName: 'Gemeente Harlingen',
    websiteUrl: 'https://www.harlingen.nl',
  },
  {
    id: 'hattem',
    name: 'Hattem',
    officialName: 'Gemeente Hattem',
    websiteUrl: 'https://www.hattem.nl',
  },
  {
    id: 'heemskerk',
    name: 'Heemskerk',
    officialName: 'Gemeente Heemskerk',
    websiteUrl: 'https://www.heemskerk.nl',
  },
  {
    id: 'heemstede',
    name: 'Heemstede',
    officialName: 'Gemeente Heemstede',
    websiteUrl: 'https://www.heemstede.nl',
  },
  {
    id: 'heerde',
    name: 'Heerde',
    officialName: 'Gemeente Heerde',
    websiteUrl: 'https://www.heerde.nl',
  },
  {
    id: 'heerenveen',
    name: 'Heerenveen',
    officialName: 'Gemeente Heerenveen',
    websiteUrl: 'https://www.heerenveen.nl',
  },
  {
    id: 'heerlen',
    name: 'Heerlen',
    officialName: 'Gemeente Heerlen',
    websiteUrl: 'https://www.heerlen.nl',
  },
  {
    id: 'heeze-leende',
    name: 'Heeze-Leende',
    officialName: 'Gemeente Heeze-Leende',
    websiteUrl: 'https://www.heeze-leende.nl',
  },
  {
    id: 'heiloo',
    name: 'Heiloo',
    officialName: 'Gemeente Heiloo',
    websiteUrl: 'https://www.heiloo.nl',
  },
  {
    id: 'hellendoorn',
    name: 'Hellendoorn',
    officialName: 'Gemeente Hellendoorn',
    websiteUrl: 'https://www.hellendoorn.nl',
  },
  {
    id: 'helmond',
    name: 'Helmond',
    officialName: 'Gemeente Helmond',
    websiteUrl: 'https://www.helmond.nl',
  },
  {
    id: 'hendrik-ido-ambacht',
    name: 'Hendrik-Ido-Ambacht',
    officialName: 'Gemeente Hendrik-Ido-Ambacht',
    websiteUrl: 'https://www.h-i-ambacht.nl',
  },
  {
    id: 'hengelo',
    name: 'Hengelo',
    officialName: 'Gemeente Hengelo',
    websiteUrl: 'https://www.hengelo.nl',
  },
  {
    id: 'den-bosch',
    name: 'Den Bosch',
    officialName: "Gemeente 's-Hertogenbosch",
    websiteUrl: 'https://www.s-hertogenbosch.nl',
  },
  {
    id: 'het-hogeland',
    name: 'Het Hogeland',
    officialName: 'Gemeente Het Hogeland',
    websiteUrl: 'https://hethogeland.nl',
  },
  {
    id: 'heumen',
    name: 'Heumen',
    officialName: 'Gemeente Heumen',
    websiteUrl: 'https://www.heumen.nl',
  },
  {
    id: 'heusden',
    name: 'Heusden',
    officialName: 'Gemeente Heusden',
    websiteUrl: 'https://www.heusden.nl',
  },
  {
    id: 'hillegom',
    name: 'Hillegom',
    officialName: 'Gemeente Hillegom',
    websiteUrl: 'https://www.hillegom.nl',
  },
  {
    id: 'hilvarenbeek',
    name: 'Hilvarenbeek',
    officialName: 'Gemeente Hilvarenbeek',
    websiteUrl: 'https://www.hilvarenbeek.nl',
  },
  {
    id: 'hilversum',
    name: 'Hilversum',
    officialName: 'Gemeente Hilversum',
    websiteUrl: 'https://www.hilversum.nl',
  },
  {
    id: 'hoeksche-waard',
    name: 'Hoeksche Waard',
    officialName: 'Gemeente Hoeksche Waard',
    websiteUrl: 'https://www.gemeentehw.nl',
  },
  {
    id: 'hof-van-twente',
    name: 'Hof van Twente',
    officialName: 'Gemeente Hof van Twente',
    websiteUrl: 'https://www.hofvantwente.nl',
  },
  {
    id: 'hollands-kroon',
    name: 'Hollands Kroon',
    officialName: 'Gemeente Hollands Kroon',
    websiteUrl: 'https://www.hollandskroon.nl',
  },
  {
    id: 'hoogeveen',
    name: 'Hoogeveen',
    officialName: 'Gemeente Hoogeveen',
    websiteUrl: 'https://www.hoogeveen.nl',
  },
  {
    id: 'hoorn',
    name: 'Hoorn',
    officialName: 'Gemeente Hoorn',
    websiteUrl: 'https://www.hoorn.nl',
  },
  {
    id: 'horst-aan-de-maas',
    name: 'Horst aan de Maas',
    officialName: 'Gemeente Horst aan de Maas',
    websiteUrl: 'https://www.horstaandemaas.nl',
  },
  {
    id: 'houten',
    name: 'Houten',
    officialName: 'Gemeente Houten',
    websiteUrl: 'https://www.houten.nl',
  },
  {
    id: 'huizen',
    name: 'Huizen',
    officialName: 'Gemeente Huizen',
    websiteUrl: 'https://www.huizen.nl',
  },
  {
    id: 'hulst',
    name: 'Hulst',
    officialName: 'Gemeente Hulst',
    websiteUrl: 'https://www.gemeentehulst.nl',
  },
  {
    id: 'ijsselstein',
    name: 'IJsselstein',
    officialName: 'Gemeente IJsselstein',
    websiteUrl: 'https://www.ijsselstein.nl',
  },
  {
    id: 'kaag-en-braassem',
    name: 'Kaag en Braassem',
    officialName: 'Gemeente Kaag en Braassem',
    websiteUrl: 'https://www.kaagenbraassem.nl',
  },
  {
    id: 'kampen',
    name: 'Kampen',
    officialName: 'Gemeente Kampen',
    websiteUrl: 'https://www.kampen.nl',
  },
  {
    id: 'kapelle',
    name: 'Kapelle',
    officialName: 'Gemeente Kapelle',
    websiteUrl: 'https://www.kapelle.nl',
  },
  {
    id: 'katwijk',
    name: 'Katwijk',
    officialName: 'Gemeente Katwijk',
    websiteUrl: 'https://www.katwijk.nl',
  },
  {
    id: 'kerkrade',
    name: 'Kerkrade',
    officialName: 'Gemeente Kerkrade',
    websiteUrl: 'https://www.kerkrade.nl',
  },
  {
    id: 'koggenland',
    name: 'Koggenland',
    officialName: 'Gemeente Koggenland',
    websiteUrl: 'https://www.koggenland.nl',
  },
  {
    id: 'krimpen-aan-den-ijssel',
    name: 'Krimpen aan den IJssel',
    officialName: 'Gemeente Krimpen aan den IJssel',
    websiteUrl: 'https://www.krimpenaandenijssel.nl',
  },
  {
    id: 'krimpenerwaard',
    name: 'Krimpenerwaard',
    officialName: 'Gemeente Krimpenerwaard',
    websiteUrl: 'https://www.krimpenerwaard.nl',
  },
  {
    id: 'laarbeek',
    name: 'Laarbeek',
    officialName: 'Gemeente Laarbeek',
    websiteUrl: 'https://www.laarbeek.nl',
  },
  {
    id: 'land-van-cuijk',
    name: 'Land van Cuijk',
    officialName: 'Gemeente Land van Cuijk',
    websiteUrl: 'https://www.landvancuijk.nl',
  },
  {
    id: 'landgraaf',
    name: 'Landgraaf',
    officialName: 'Gemeente Landgraaf',
    websiteUrl: 'https://www.landgraaf.nl',
  },
  {
    id: 'landsmeer',
    name: 'Landsmeer',
    officialName: 'Gemeente Landsmeer',
    websiteUrl: 'https://www.landsmeer.nl',
  },
  {
    id: 'lansingerland',
    name: 'Lansingerland',
    officialName: 'Gemeente Lansingerland',
    websiteUrl: 'https://www.lansingerland.nl',
  },
  {
    id: 'laren',
    name: 'Laren',
    officialName: 'Gemeente Laren',
    websiteUrl: 'https://www.laren.nl',
  },
  {
    id: 'leeuwarden',
    name: 'Leeuwarden',
    officialName: 'Gemeente Leeuwarden',
    websiteUrl: 'https://www.leeuwarden.nl',
  },
  {
    id: 'leiden',
    name: 'Leiden',
    officialName: 'Gemeente Leiden',
    websiteUrl: 'https://www.leiden.nl',
  },
  {
    id: 'leiderdorp',
    name: 'Leiderdorp',
    officialName: 'Gemeente Leiderdorp',
    websiteUrl: 'https://www.leiderdorp.nl',
  },
  {
    id: 'leidschendam-voorburg',
    name: 'Leidschendam-Voorburg',
    officialName: 'Gemeente Leidschendam-Voorburg',
    websiteUrl: 'https://www.leidschendam-voorburg.nl',
  },
  {
    id: 'lelystad',
    name: 'Lelystad',
    officialName: 'Gemeente Lelystad',
    websiteUrl: 'https://www.lelystad.nl',
  },
  {
    id: 'leudal',
    name: 'Leudal',
    officialName: 'Gemeente Leudal',
    websiteUrl: 'https://www.leudal.nl',
  },
  {
    id: 'leusden',
    name: 'Leusden',
    officialName: 'Gemeente Leusden',
    websiteUrl: 'https://www.leusden.nl',
  },
  {
    id: 'lingewaard',
    name: 'Lingewaard',
    officialName: 'Gemeente Lingewaard',
    websiteUrl: 'https://www.lingewaard.nl',
  },
  {
    id: 'lisse',
    name: 'Lisse',
    officialName: 'Gemeente Lisse',
    websiteUrl: 'https://www.lisse.nl',
  },
  {
    id: 'lochem',
    name: 'Lochem',
    officialName: 'Gemeente Lochem',
    websiteUrl: 'https://www.lochem.nl',
  },
  {
    id: 'loon-op-zand',
    name: 'Loon op Zand',
    officialName: 'Gemeente Loon op Zand',
    websiteUrl: 'https://www.loonopzand.nl',
  },
  {
    id: 'lopik',
    name: 'Lopik',
    officialName: 'Gemeente Lopik',
    websiteUrl: 'https://www.lopik.nl',
  },
  {
    id: 'losser',
    name: 'Losser',
    officialName: 'Gemeente Losser',
    websiteUrl: 'https://www.losser.nl',
  },
  {
    id: 'maasdriel',
    name: 'Maasdriel',
    officialName: 'Gemeente Maasdriel',
    websiteUrl: 'https://www.maasdriel.nl',
  },
  {
    id: 'maasgouw',
    name: 'Maasgouw',
    officialName: 'Gemeente Maasgouw',
    websiteUrl: 'https://www.gemeentemaasgouw.nl',
  },
  {
    id: 'maashorst',
    name: 'Maashorst',
    officialName: 'Gemeente Maashorst',
    websiteUrl: 'https://www.gemeentemaashorst.nl',
  },
  {
    id: 'maassluis',
    name: 'Maassluis',
    officialName: 'Gemeente Maassluis',
    websiteUrl: 'https://www.maassluis.nl',
  },
  {
    id: 'maastricht',
    name: 'Maastricht',
    officialName: 'Gemeente Maastricht',
    websiteUrl: 'https://www.gemeentemaastricht.nl',
  },
  {
    id: 'medemblik',
    name: 'Medemblik',
    officialName: 'Gemeente Medemblik',
    websiteUrl: 'https://www.medemblik.nl',
  },
  {
    id: 'meerssen',
    name: 'Meerssen',
    officialName: 'Gemeente Meerssen',
    websiteUrl: 'https://www.meerssen.nl',
  },
  {
    id: 'meierijstad',
    name: 'Meierijstad',
    officialName: 'Gemeente Meierijstad',
    websiteUrl: 'https://www.meierijstad.nl',
  },
  {
    id: 'meppel',
    name: 'Meppel',
    officialName: 'Gemeente Meppel',
    websiteUrl: 'https://www.meppel.nl',
  },
  {
    id: 'middelburg',
    name: 'Middelburg',
    officialName: 'Gemeente Middelburg',
    websiteUrl: 'https://www.middelburg.nl',
  },
  {
    id: 'midden-delfland',
    name: 'Midden-Delfland',
    officialName: 'Gemeente Midden-Delfland',
    websiteUrl: 'https://www.middendelfland.nl',
  },
  {
    id: 'midden-drenthe',
    name: 'Midden-Drenthe',
    officialName: 'Gemeente Midden-Drenthe',
    websiteUrl: 'https://www.middendrenthe.nl',
  },
  {
    id: 'midden-groningen',
    name: 'Midden-Groningen',
    officialName: 'Gemeente Midden-Groningen',
    websiteUrl: 'https://www.midden-groningen.nl',
  },
  {
    id: 'moerdijk',
    name: 'Moerdijk',
    officialName: 'Gemeente Moerdijk',
    websiteUrl: 'https://www.moerdijk.nl',
  },
  {
    id: 'molenlanden',
    name: 'Molenlanden',
    officialName: 'Gemeente Molenlanden',
    websiteUrl: 'https://www.molenlanden.nl',
  },
  {
    id: 'montferland',
    name: 'Montferland',
    officialName: 'Gemeente Montferland',
    websiteUrl: 'https://www.montferland.info',
  },
  {
    id: 'montfoort',
    name: 'Montfoort',
    officialName: 'Gemeente Montfoort',
    websiteUrl: 'https://www.montfoort.nl',
  },
  {
    id: 'mook-en-middelaar',
    name: 'Mook en Middelaar',
    officialName: 'Gemeente Mook en Middelaar',
    websiteUrl: 'https://www.mookenmiddelaar.nl',
  },
  {
    id: 'neder-betuwe',
    name: 'Neder-Betuwe',
    officialName: 'Gemeente Neder-Betuwe',
    websiteUrl: 'https://www.nederbetuwe.nl',
  },
  {
    id: 'nederweert',
    name: 'Nederweert',
    officialName: 'Gemeente Nederweert',
    websiteUrl: 'https://www.nederweert.nl',
  },
  {
    id: 'nieuwegein',
    name: 'Nieuwegein',
    officialName: 'Gemeente Nieuwegein',
    websiteUrl: 'https://www.nieuwegein.nl',
  },
  {
    id: 'nieuwkoop',
    name: 'Nieuwkoop',
    officialName: 'Gemeente Nieuwkoop',
    websiteUrl: 'https://www.nieuwkoop.nl',
  },
  {
    id: 'nijkerk',
    name: 'Nijkerk',
    officialName: 'Gemeente Nijkerk',
    websiteUrl: 'https://www.nijkerk.eu',
  },
  {
    id: 'nijmegen',
    name: 'Nijmegen',
    officialName: 'Gemeente Nijmegen',
    websiteUrl: 'https://www.nijmegen.nl',
  },
  {
    id: 'nissewaard',
    name: 'Nissewaard',
    officialName: 'Gemeente Nissewaard',
    websiteUrl: 'https://www.nissewaard.nl',
  },
  {
    id: 'noardeast-fryslân',
    name: 'Noardeast-Fryslân',
    officialName: 'Gemeente Noardeast-Fryslân',
    websiteUrl: 'https://www.noardeast-fryslan.nl',
  },
  {
    id: 'noord-beveland',
    name: 'Noord-Beveland',
    officialName: 'Gemeente Noord-Beveland',
    websiteUrl: 'https://www.noord-beveland.nl',
  },
  {
    id: 'noordenveld',
    name: 'Noordenveld',
    officialName: 'Gemeente Noordenveld',
    websiteUrl: 'https://www.noordenveld.nl',
  },
  {
    id: 'noordoostpolder',
    name: 'Noordoostpolder',
    officialName: 'Gemeente Noordoostpolder',
    websiteUrl: 'https://www.noordoostpolder.nl',
  },
  {
    id: 'noordwijk',
    name: 'Noordwijk',
    officialName: 'Gemeente Noordwijk',
    websiteUrl: 'https://www.noordwijk.nl',
  },
  {
    id: 'nuenen-c-a',
    name: 'Nuenen c.a.',
    officialName: 'Gemeente Nuenen, Gerwen en Nederwetten',
    websiteUrl: 'https://www.nuenen.nl',
  },
  {
    id: 'nunspeet',
    name: 'Nunspeet',
    officialName: 'Gemeente Nunspeet',
    websiteUrl: 'https://www.nunspeet.nl',
  },
  {
    id: 'oegstgeest',
    name: 'Oegstgeest',
    officialName: 'Gemeente Oegstgeest',
    websiteUrl: 'https://www.oegstgeest.nl',
  },
  {
    id: 'oirschot',
    name: 'Oirschot',
    officialName: 'Gemeente Oirschot',
    websiteUrl: 'https://www.oirschot.nl',
  },
  {
    id: 'oisterwijk',
    name: 'Oisterwijk',
    officialName: 'Gemeente Oisterwijk',
    websiteUrl: 'https://www.oisterwijk.nl',
  },
  {
    id: 'oldambt',
    name: 'Oldambt',
    officialName: 'Gemeente Oldambt',
    websiteUrl: 'https://www.gemeente-oldambt.nl',
  },
  {
    id: 'oldebroek',
    name: 'Oldebroek',
    officialName: 'Gemeente Oldebroek',
    websiteUrl: 'https://www.oldebroek.nl',
  },
  {
    id: 'oldenzaal',
    name: 'Oldenzaal',
    officialName: 'Gemeente Oldenzaal',
    websiteUrl: 'https://www.oldenzaal.nl',
  },
  {
    id: 'olst-wijhe',
    name: 'Olst-Wijhe',
    officialName: 'Gemeente Olst-Wijhe',
    websiteUrl: 'https://www.olst-wijhe.nl',
  },
  {
    id: 'ommen',
    name: 'Ommen',
    officialName: 'Gemeente Ommen',
    websiteUrl: 'https://www.ommen.nl',
  },
  {
    id: 'oost-gelre',
    name: 'Oost Gelre',
    officialName: 'Gemeente Oost Gelre',
    websiteUrl: 'https://www.oostgelre.nl',
  },
  {
    id: 'oosterhout',
    name: 'Oosterhout',
    officialName: 'Gemeente Oosterhout',
    websiteUrl: 'https://www.oosterhout.nl',
  },
  {
    id: 'ooststellingwerf',
    name: 'Ooststellingwerf',
    officialName: 'Gemeente Ooststellingwerf',
    websiteUrl: 'https://www.ooststellingwerf.nl',
  },
  {
    id: 'oostzaan',
    name: 'Oostzaan',
    officialName: 'Gemeente Oostzaan',
    websiteUrl: 'https://www.oostzaan.nl',
  },
  {
    id: 'opmeer',
    name: 'Opmeer',
    officialName: 'Gemeente Opmeer',
    websiteUrl: 'https://www.opmeer.nl',
  },
  {
    id: 'opsterland',
    name: 'Opsterland',
    officialName: 'Gemeente Opsterland',
    websiteUrl: 'https://www.opsterland.nl',
  },
  {
    id: 'oss',
    name: 'Oss',
    officialName: 'Gemeente Oss',
    websiteUrl: 'https://www.oss.nl',
  },
  {
    id: 'oude-ijsselstreek',
    name: 'Oude IJsselstreek',
    officialName: 'Gemeente Oude IJsselstreek',
    websiteUrl: 'https://www.oude-ijsselstreek.nl',
  },
  {
    id: 'ouder-amstel',
    name: 'Ouder-Amstel',
    officialName: 'Gemeente Ouder-Amstel',
    websiteUrl: 'https://www.ouder-amstel.nl',
  },
  {
    id: 'oudewater',
    name: 'Oudewater',
    officialName: 'Gemeente Oudewater',
    websiteUrl: 'https://www.oudewater.nl',
  },
  {
    id: 'overbetuwe',
    name: 'Overbetuwe',
    officialName: 'Gemeente Overbetuwe',
    websiteUrl: 'https://www.overbetuwe.nl',
  },
  {
    id: 'papendrecht',
    name: 'Papendrecht',
    officialName: 'Gemeente Papendrecht',
    websiteUrl: 'https://www.papendrecht.nl',
  },
  {
    id: 'peel-en-maas',
    name: 'Peel en Maas',
    officialName: 'Gemeente Peel en Maas',
    websiteUrl: 'https://www.peelenmaas.nl',
  },
  {
    id: 'pekela',
    name: 'Pekela',
    officialName: 'Gemeente Pekela',
    websiteUrl: 'https://www.pekela.nl',
  },
  {
    id: 'pijnacker-nootdorp',
    name: 'Pijnacker-Nootdorp',
    officialName: 'Gemeente Pijnacker-Nootdorp',
    websiteUrl: 'https://www.pijnacker-nootdorp.nl',
  },
  {
    id: 'purmerend',
    name: 'Purmerend',
    officialName: 'Gemeente Purmerend',
    websiteUrl: 'https://www.purmerend.nl',
  },
  {
    id: 'putten',
    name: 'Putten',
    officialName: 'Gemeente Putten',
    websiteUrl: 'https://www.putten.nl',
  },
  {
    id: 'raalte',
    name: 'Raalte',
    officialName: 'Gemeente Raalte',
    websiteUrl: 'https://www.raalte.nl',
  },
  {
    id: 'reimerswaal',
    name: 'Reimerswaal',
    officialName: 'Gemeente Reimerswaal',
    websiteUrl: 'https://www.reimerswaal.nl',
  },
  {
    id: 'renkum',
    name: 'Renkum',
    officialName: 'Gemeente Renkum',
    websiteUrl: 'https://www.renkum.nl',
  },
  {
    id: 'renswoude',
    name: 'Renswoude',
    officialName: 'Gemeente Renswoude',
    websiteUrl: 'https://www.renswoude.nl',
  },
  {
    id: 'reusel-de-mierden',
    name: 'Reusel-De Mierden',
    officialName: 'Gemeente Reusel-De Mierden',
    websiteUrl: 'https://www.reuseldemierden.nl',
  },
  {
    id: 'rheden',
    name: 'Rheden',
    officialName: 'Gemeente Rheden',
    websiteUrl: 'https://www.rheden.nl',
  },
  {
    id: 'rhenen',
    name: 'Rhenen',
    officialName: 'Gemeente Rhenen',
    websiteUrl: 'https://www.rhenen.nl',
  },
  {
    id: 'ridderkerk',
    name: 'Ridderkerk',
    officialName: 'Gemeente Ridderkerk',
    websiteUrl: 'https://www.ridderkerk.nl',
  },
  {
    id: 'rijssen-holten',
    name: 'Rijssen-Holten',
    officialName: 'Gemeente Rijssen-Holten',
    websiteUrl: 'https://www.rijssen-holten.nl',
  },
  {
    id: 'rijswijk',
    name: 'Rijswijk',
    officialName: 'Gemeente Rijswijk',
    websiteUrl: 'https://www.rijswijk.nl',
  },
  {
    id: 'roerdalen',
    name: 'Roerdalen',
    officialName: 'Gemeente Roerdalen',
    websiteUrl: 'https://www.roerdalen.nl',
  },
  {
    id: 'roermond',
    name: 'Roermond',
    officialName: 'Gemeente Roermond',
    websiteUrl: 'https://www.roermond.nl',
  },
  {
    id: 'roosendaal',
    name: 'Roosendaal',
    officialName: 'Gemeente Roosendaal',
    websiteUrl: 'https://www.roosendaal.nl',
  },
  {
    id: 'rotterdam',
    name: 'Rotterdam',
    officialName: 'Gemeente Rotterdam',
    websiteUrl: 'https://www.rotterdam.nl',
  },
  {
    id: 'rozendaal',
    name: 'Rozendaal',
    officialName: 'Gemeente Rozendaal',
    websiteUrl: 'https://www.rozendaal.nl',
  },
  {
    id: 'rucphen',
    name: 'Rucphen',
    officialName: 'Gemeente Rucphen',
    websiteUrl: 'https://www.rucphen.nl',
  },
  {
    id: 'schagen',
    name: 'Schagen',
    officialName: 'Gemeente Schagen',
    websiteUrl: 'https://www.schagen.nl',
  },
  {
    id: 'scherpenzeel',
    name: 'Scherpenzeel',
    officialName: 'Gemeente Scherpenzeel',
    websiteUrl: 'https://www.scherpenzeel.nl',
  },
  {
    id: 'schiedam',
    name: 'Schiedam',
    officialName: 'Gemeente Schiedam',
    websiteUrl: 'https://www.schiedam.nl',
  },
  {
    id: 'schiermonnikoog',
    name: 'Schiermonnikoog',
    officialName: 'Gemeente Schiermonnikoog',
    websiteUrl: 'https://www.schiermonnikoog.nl',
  },
  {
    id: 'schouwen-duiveland',
    name: 'Schouwen-Duiveland',
    officialName: 'Gemeente Schouwen-Duiveland',
    websiteUrl: 'https://www.schouwen-duiveland.nl',
  },
  {
    id: 'simpelveld',
    name: 'Simpelveld',
    officialName: 'Gemeente Simpelveld',
    websiteUrl: 'https://www.simpelveld.nl',
  },
  {
    id: 'sint-michielsgestel',
    name: 'Sint-Michielsgestel',
    officialName: 'Gemeente Sint-Michielsgestel',
    websiteUrl: 'https://www.sint-michielsgestel.nl',
  },
  {
    id: 'sittard-geleen',
    name: 'Sittard-Geleen',
    officialName: 'Gemeente Sittard-Geleen',
    websiteUrl: 'https://www.sittard-geleen.nl',
  },
  {
    id: 'sliedrecht',
    name: 'Sliedrecht',
    officialName: 'Gemeente Sliedrecht',
    websiteUrl: 'https://www.sliedrecht.nl',
  },
  {
    id: 'sluis',
    name: 'Sluis',
    officialName: 'Gemeente Sluis',
    websiteUrl: 'https://www.gemeentesluis.nl',
  },
  {
    id: 'smallingerland',
    name: 'Smallingerland',
    officialName: 'Gemeente Smallingerland',
    websiteUrl: 'https://www.smallingerland.nl',
  },
  {
    id: 'soest',
    name: 'Soest',
    officialName: 'Gemeente Soest',
    websiteUrl: 'https://www.soest.nl',
  },
  {
    id: 'someren',
    name: 'Someren',
    officialName: 'Gemeente Someren',
    websiteUrl: 'https://www.someren.nl',
  },
  {
    id: 'son-en-breugel',
    name: 'Son en Breugel',
    officialName: 'Gemeente Son en Breugel',
    websiteUrl: 'https://www.sonenbreugel.nl',
  },
  {
    id: 'stadskanaal',
    name: 'Stadskanaal',
    officialName: 'Gemeente Stadskanaal',
    websiteUrl: 'https://www.stadskanaal.nl',
  },
  {
    id: 'staphorst',
    name: 'Staphorst',
    officialName: 'Gemeente Staphorst',
    websiteUrl: 'https://www.staphorst.nl',
  },
  {
    id: 'stede-broec',
    name: 'Stede Broec',
    officialName: 'Gemeente Stede Broec',
    websiteUrl: 'https://www.stedebroec.nl',
  },
  {
    id: 'steenbergen',
    name: 'Steenbergen',
    officialName: 'Gemeente Steenbergen',
    websiteUrl: 'https://www.gemeente-steenbergen.nl',
  },
  {
    id: 'steenwijkerland',
    name: 'Steenwijkerland',
    officialName: 'Gemeente Steenwijkerland',
    websiteUrl: 'https://www.steenwijkerland.nl',
  },
  {
    id: 'stein',
    name: 'Stein',
    officialName: 'Gemeente Stein',
    websiteUrl: 'https://www.gemeentestein.nl',
  },
  {
    id: 'stichtse-vecht',
    name: 'Stichtse Vecht',
    officialName: 'Gemeente Stichtse Vecht',
    websiteUrl: 'https://www.stichtsevecht.nl',
  },
  {
    id: 'súdwest-fryslân',
    name: 'Súdwest-Fryslân',
    officialName: 'Gemeente Súdwest-Fryslân',
    websiteUrl: 'https://www.sudwestfryslan.nl',
  },
  {
    id: 'terneuzen',
    name: 'Terneuzen',
    officialName: 'Gemeente Terneuzen',
    websiteUrl: 'https://www.terneuzen.nl',
  },
  {
    id: 'terschelling',
    name: 'Terschelling',
    officialName: 'Gemeente Terschelling',
    websiteUrl: 'https://www.terschelling.nl',
  },
  {
    id: 'texel',
    name: 'Texel',
    officialName: 'Gemeente Texel',
    websiteUrl: 'https://www.texel.nl',
  },
  {
    id: 'teylingen',
    name: 'Teylingen',
    officialName: 'Gemeente Teylingen',
    websiteUrl: 'https://www.teylingen.nl',
  },
  {
    id: 'tholen',
    name: 'Tholen',
    officialName: 'Gemeente Tholen',
    websiteUrl: 'https://www.tholen.nl',
  },
  {
    id: 'tiel',
    name: 'Tiel',
    officialName: 'Gemeente Tiel',
    websiteUrl: 'https://www.tiel.nl',
  },
  {
    id: 'tilburg',
    name: 'Tilburg',
    officialName: 'Gemeente Tilburg',
    websiteUrl: 'https://www.tilburg.nl',
  },
  {
    id: 'tubbergen',
    name: 'Tubbergen',
    officialName: 'Gemeente Tubbergen',
    websiteUrl: 'https://www.tubbergen.nl',
  },
  {
    id: 'twenterand',
    name: 'Twenterand',
    officialName: 'Gemeente Twenterand',
    websiteUrl: 'https://www.twenterand.nl',
  },
  {
    id: 'tynaarlo',
    name: 'Tynaarlo',
    officialName: 'Gemeente Tynaarlo',
    websiteUrl: 'https://www.tynaarlo.nl',
  },
  {
    id: 'tytsjerksteradiel',
    name: 'Tytsjerksteradiel',
    officialName: 'Gemeente Tytsjerksteradiel',
    websiteUrl: 'https://www.t-diel.nl',
  },
  {
    id: 'uitgeest',
    name: 'Uitgeest',
    officialName: 'Gemeente Uitgeest',
    websiteUrl: 'https://www.uitgeest.nl',
  },
  {
    id: 'uithoorn',
    name: 'Uithoorn',
    officialName: 'Gemeente Uithoorn',
    websiteUrl: 'https://www.uithoorn.nl',
  },
  {
    id: 'urk',
    name: 'Urk',
    officialName: 'Gemeente Urk',
    websiteUrl: 'https://www.urk.nl',
  },
  {
    id: 'utrecht',
    name: 'Utrecht',
    officialName: 'Gemeente Utrecht',
    websiteUrl: 'https://www.utrecht.nl',
  },
  {
    id: 'utrechtse-heuvelrug',
    name: 'Utrechtse Heuvelrug',
    officialName: 'Gemeente Utrechtse Heuvelrug',
    websiteUrl: 'https://www.heuvelrug.nl',
  },
  {
    id: 'vaals',
    name: 'Vaals',
    officialName: 'Gemeente Vaals',
    websiteUrl: 'https://www.vaals.nl',
  },
  {
    id: 'valkenburg-aan-de-geul',
    name: 'Valkenburg aan de Geul',
    officialName: 'Gemeente Valkenburg aan de Geul',
    websiteUrl: 'https://www.valkenburg.nl',
  },
  {
    id: 'valkenswaard',
    name: 'Valkenswaard',
    officialName: 'Gemeente Valkenswaard',
    websiteUrl: 'https://www.valkenswaard.nl',
  },
  {
    id: 'veendam',
    name: 'Veendam',
    officialName: 'Gemeente Veendam',
    websiteUrl: 'https://www.veendam.nl',
  },
  {
    id: 'veenendaal',
    name: 'Veenendaal',
    officialName: 'Gemeente Veenendaal',
    websiteUrl: 'https://www.veenendaal.nl',
  },
  {
    id: 'veere',
    name: 'Veere',
    officialName: 'Gemeente Veere',
    websiteUrl: 'https://www.veere.nl',
  },
  {
    id: 'veldhoven',
    name: 'Veldhoven',
    officialName: 'Gemeente Veldhoven',
    websiteUrl: 'https://www.veldhoven.nl',
  },
  {
    id: 'velsen',
    name: 'Velsen',
    officialName: 'Gemeente Velsen',
    websiteUrl: 'https://www.velsen.nl',
  },
  {
    id: 'venlo',
    name: 'Venlo',
    officialName: 'Gemeente Venlo',
    websiteUrl: 'https://www.venlo.nl',
  },
  {
    id: 'venray',
    name: 'Venray',
    officialName: 'Gemeente Venray',
    websiteUrl: 'https://www.venray.nl',
  },
  {
    id: 'vijfheerenlanden',
    name: 'Vijfheerenlanden',
    officialName: 'Gemeente Vijfheerenlanden',
    websiteUrl: 'https://www.vijfheerenlanden.nl',
  },
  {
    id: 'vlaardingen',
    name: 'Vlaardingen',
    officialName: 'Gemeente Vlaardingen',
    websiteUrl: 'https://www.vlaardingen.nl',
  },
  {
    id: 'vlieland',
    name: 'Vlieland',
    officialName: 'Gemeente Vlieland',
    websiteUrl: 'https://www.vlieland.nl',
  },
  {
    id: 'vlissingen',
    name: 'Vlissingen',
    officialName: 'Gemeente Vlissingen',
    websiteUrl: 'https://www.vlissingen.nl',
  },
  {
    id: 'voerendaal',
    name: 'Voerendaal',
    officialName: 'Gemeente Voerendaal',
    websiteUrl: 'https://www.voerendaal.nl',
  },
  {
    id: 'voorne-aan-zee',
    name: 'Voorne aan Zee',
    officialName: 'Gemeente Voorne aan Zee',
    websiteUrl: 'https://www.voorneaanzee.nl',
  },
  {
    id: 'voorschoten',
    name: 'Voorschoten',
    officialName: 'Gemeente Voorschoten',
    websiteUrl: 'https://www.voorschoten.nl',
  },
  {
    id: 'voorst',
    name: 'Voorst',
    officialName: 'Gemeente Voorst',
    websiteUrl: 'https://www.voorst.nl',
  },
  {
    id: 'vught',
    name: 'Vught',
    officialName: 'Gemeente Vught',
    websiteUrl: 'https://www.vught.nl',
  },
  {
    id: 'waadhoeke',
    name: 'Waadhoeke',
    officialName: 'Gemeente Waadhoeke',
    websiteUrl: 'https://www.waadhoeke.nl',
  },
  {
    id: 'waalre',
    name: 'Waalre',
    officialName: 'Gemeente Waalre',
    websiteUrl: 'https://www.waalre.nl',
  },
  {
    id: 'waalwijk',
    name: 'Waalwijk',
    officialName: 'Gemeente Waalwijk',
    websiteUrl: 'https://www.waalwijk.nl',
  },
  {
    id: 'waddinxveen',
    name: 'Waddinxveen',
    officialName: 'Gemeente Waddinxveen',
    websiteUrl: 'https://www.waddinxveen.nl',
  },
  {
    id: 'wageningen',
    name: 'Wageningen',
    officialName: 'Gemeente Wageningen',
    websiteUrl: 'https://www.wageningen.nl',
  },
  {
    id: 'wassenaar',
    name: 'Wassenaar',
    officialName: 'Gemeente Wassenaar',
    websiteUrl: 'https://www.wassenaar.nl',
  },
  {
    id: 'waterland',
    name: 'Waterland',
    officialName: 'Gemeente Waterland',
    websiteUrl: 'https://www.waterland.nl',
  },
  {
    id: 'weert',
    name: 'Weert',
    officialName: 'Gemeente Weert',
    websiteUrl: 'https://www.weert.nl',
  },
  {
    id: 'west-betuwe',
    name: 'West Betuwe',
    officialName: 'Gemeente West Betuwe',
    websiteUrl: 'https://www.westbetuwe.nl',
  },
  {
    id: 'west-maas-en-waal',
    name: 'West Maas en Waal',
    officialName: 'Gemeente West Maas en Waal',
    websiteUrl: 'https://www.westmaasenwaal.nl',
  },
  {
    id: 'westerkwartier',
    name: 'Westerkwartier',
    officialName: 'Gemeente Westerkwartier',
    websiteUrl: 'https://www.westerkwartier.nl',
  },
  {
    id: 'westerveld',
    name: 'Westerveld',
    officialName: 'Gemeente Westerveld',
    websiteUrl: 'https://www.gemeentewesterveld.nl',
  },
  {
    id: 'westervoort',
    name: 'Westervoort',
    officialName: 'Gemeente Westervoort',
    websiteUrl: 'https://www.westervoort.nl',
  },
  {
    id: 'westerwolde',
    name: 'Westerwolde',
    officialName: 'Gemeente Westerwolde',
    websiteUrl: 'https://www.westerwolde.nl',
  },
  {
    id: 'westland',
    name: 'Westland',
    officialName: 'Gemeente Westland',
    websiteUrl: 'https://www.gemeentewestland.nl',
  },
  {
    id: 'weststellingwerf',
    name: 'Weststellingwerf',
    officialName: 'Gemeente Weststellingwerf',
    websiteUrl: 'https://www.weststellingwerf.nl',
  },
  {
    id: 'wierden',
    name: 'Wierden',
    officialName: 'Gemeente Wierden',
    websiteUrl: 'https://www.wierden.nl',
  },
  {
    id: 'wijchen',
    name: 'Wijchen',
    officialName: 'Gemeente Wijchen',
    websiteUrl: 'https://www.wijchen.nl',
  },
  {
    id: 'wijdemeren',
    name: 'Wijdemeren',
    officialName: 'Gemeente Wijdemeren',
    websiteUrl: 'https://www.wijdemeren.nl',
  },
  {
    id: 'wijk-bij-duurstede',
    name: 'Wijk bij Duurstede',
    officialName: 'Gemeente Wijk bij Duurstede',
    websiteUrl: 'https://www.wijkbijduurstede.nl',
  },
  {
    id: 'winterswijk',
    name: 'Winterswijk',
    officialName: 'Gemeente Winterswijk',
    websiteUrl: 'https://www.winterswijk.nl',
  },
  {
    id: 'woensdrecht',
    name: 'Woensdrecht',
    officialName: 'Gemeente Woensdrecht',
    websiteUrl: 'https://www.woensdrecht.nl',
  },
  {
    id: 'woerden',
    name: 'Woerden',
    officialName: 'Gemeente Woerden',
    websiteUrl: 'https://www.woerden.nl',
  },
  {
    id: 'wormerland',
    name: 'Wormerland',
    officialName: 'Gemeente Wormerland',
    websiteUrl: 'https://www.wormerland.nl',
  },
  {
    id: 'woudenberg',
    name: 'Woudenberg',
    officialName: 'Gemeente Woudenberg',
    websiteUrl: 'https://www.woudenberg.nl',
  },
  {
    id: 'zaanstad',
    name: 'Zaanstad',
    officialName: 'Gemeente Zaanstad',
    websiteUrl: 'https://www.zaanstad.nl',
  },
  {
    id: 'zaltbommel',
    name: 'Zaltbommel',
    officialName: 'Gemeente Zaltbommel',
    websiteUrl: 'https://www.zaltbommel.nl',
  },
  {
    id: 'zandvoort',
    name: 'Zandvoort',
    officialName: 'Gemeente Zandvoort',
    websiteUrl: 'https://www.zandvoort.nl',
  },
  {
    id: 'zeewolde',
    name: 'Zeewolde',
    officialName: 'Gemeente Zeewolde',
    websiteUrl: 'https://www.zeewolde.nl',
  },
  {
    id: 'zeist',
    name: 'Zeist',
    officialName: 'Gemeente Zeist',
    websiteUrl: 'https://www.zeist.nl',
  },
  {
    id: 'zevenaar',
    name: 'Zevenaar',
    officialName: 'Gemeente Zevenaar',
    websiteUrl: 'https://www.zevenaar.nl',
  },
  {
    id: 'zoetermeer',
    name: 'Zoetermeer',
    officialName: 'Gemeente Zoetermeer',
    websiteUrl: 'https://www.zoetermeer.nl',
  },
  {
    id: 'zoeterwoude',
    name: 'Zoeterwoude',
    officialName: 'Gemeente Zoeterwoude',
    websiteUrl: 'https://www.zoeterwoude.nl',
  },
  {
    id: 'zuidplas',
    name: 'Zuidplas',
    officialName: 'Gemeente Zuidplas',
    websiteUrl: 'https://www.zuidplas.nl',
  },
  {
    id: 'zundert',
    name: 'Zundert',
    officialName: 'Gemeente Zundert',
    websiteUrl: 'https://www.zundert.nl',
  },
  {
    id: 'zutphen',
    name: 'Zutphen',
    officialName: 'Gemeente Zutphen',
    websiteUrl: 'https://www.zutphen.nl',
  },
  {
    id: 'zwartewaterland',
    name: 'Zwartewaterland',
    officialName: 'Gemeente Zwartewaterland',
    websiteUrl: 'https://www.zwartewaterland.nl',
  },
  {
    id: 'zwijndrecht',
    name: 'Zwijndrecht',
    officialName: 'Gemeente Zwijndrecht',
    websiteUrl: 'https://www.zwijndrecht.nl',
  },
  {
    id: 'zwolle',
    name: 'Zwolle',
    officialName: 'Gemeente Zwolle',
    websiteUrl: 'https://www.zwolle.nl',
  },
];
